version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
        
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/simulator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "weekly"
